# fly.toml app configuration file generated for goob-bot on 2025-12-02T11:07:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'goob-bot'
primary_region = 'iad'

[build]

[experimental]
  auto_rollback = true

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "node dist/deploy.js"
